version: '3.7'
services:

  legacywebshop:
    build:
      context: .
      dockerfile: ./eshop/docker/Dockerfile
    ports:
      - "8888:8080"
    networks:
      local_net:
          aliases:
              - legacywebshop
              
  userdb:
    build:
      context: ./hsqldb
      dockerfile: ./Dockerfile
      args:
        dbname: userdb
    ports: 
      - "8763:9001"
    networks:
      local_net:
        aliases:
          - userdb
  
  categorydb:
    build:
      context: ./hsqldb
      dockerfile: ./Dockerfile
      args:
        dbname: categorydb
    ports: 
      - "8767:9001"
    networks:
      local_net:
        aliases:
          - categorydb
  
  productdb:
    build:
      context: ./hsqldb
      dockerfile: ./Dockerfile
      args:
        dbname: productdb
    ports: 
      - "8765:9001"
    networks:
      local_net:
        aliases:
          - productdb
  
  eureka:
    build:
      context: .
      dockerfile: ./service.Dockerfile
      args:
        sname: eureka
        sPort: 8761
    ports:
      - "8761:8761"
    networks:
      local_net:
        aliases:
          - eureka
  
  oauth:
    depends_on:
      - eureka
    build:
      context: .
      dockerfile: ./service.Dockerfile
      args:
        sname: oauth
        sPort: 8081
    ports:
      - "8081:8081"
    networks:
      local_net:
        aliases:
          - oauth
  
  zuul:
    depends_on:
      - eureka
    build:
      context: .
      dockerfile: ./service.Dockerfile
      args:
        sname: zuul
        sPort: 8770
    ports:
      - "8770:8770"
    networks:
      local_net:
        aliases:
          - zuul
  
  dashboard:
    depends_on:
      - eureka
    build:
      context: .
      dockerfile: ./service.Dockerfile
      args:
        sname: dashboard
        sPort: 8769
    ports:
      - "8769:8769"
    networks:
      local_net:
        aliases:
          - dashboard
  
  userservice:
    depends_on:
      - eureka
      - userdb
    build:
      context: .
      dockerfile: ./service.Dockerfile
      args:
        sname: userservice
        sPort: 8762
    ports: 
      - "8762:8762"
    networks:
      local_net:
        aliases:
          - userservice
  
  categoryservice:
    depends_on:
      - eureka
      - categorydb
    build:
      context: .
      dockerfile: ./service.Dockerfile
      args:
        sname: categoryservice
        sPort: 8766
    ports: 
      - "8766:8766"
    networks:
      local_net:
        aliases:
          - categoryservice
  
  productservice:
    depends_on:
      - eureka
      - productdb
    build:
      context: .
      dockerfile: ./service.Dockerfile
      args:
        sname: productservice
        sPort: 8764
    ports:
      - "8764:8764"
    networks:
      local_net:
        aliases:
          - productservice
  
  catalogservice:
    depends_on:
      - eureka
    build:
      context: .
      dockerfile: ./service.Dockerfile
      args:
        sname: catalogservice
        sPort: 8768
    ports: 
      - "8768:8768"
    networks:
      local_net:
        aliases:
          - catalogservice

networks: 
  local_net:
    driver: bridge