server:
  port: 8001
spring:
  application:
    name: product-service
  jpa:
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:postgresql://database:5432/db
    username: admin
    password: password1234
eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka:8761/eureka/
  instance:
    preferIpAddress: true
    leaseRenewalIntervalInSeconds: 5
    metadataMap:
      instanceId: "${spring.application.name}:${random.value}"
auth:
  server:
    url: http://oauth:8090/auth/oauth/check_token
    clientId: messaging-client
    clientsecret: secret

