server:
  port: 8020

eureka:
  instance:
    leaseRenewalIntervalInSeconds: 10
    statusPageUrlPath: /info
    healthCheckUrlPath: /health

management:
  endpoints:
    web:
      exposure:
        include:
          - "*"

zuul:
  sensitive-headers: Cookie,Set-Cookie
  ignored-services:
    - '*'
  ribbon:
    eager-load:
      enabled: true
  #prefix: /webshop
  routes:
    user-service:
      path: /users/**
      service-id: user-service
      strip-prefix: false
    catalog-service:
      path: /**
      service-id: catalog-service
      strip-prefix: true
    oauth:
      path: /auth/**
      service-id: oauth
      strip-prefix: false

#auth:
#  server:
#    url: http://oauth:8090/auth/oauth/check_token
#    clientId: messaging-client
#    clientSecret: "{noop}secret"

spring:
  security:
    oauth2:
      client:
        clientId: messaging-client
        clientSecret: "{noop}secret"
      resource:
        tokenInfoUri: http://oauth:8090/auth/oauth/check_token
        userInfoUri: http://oauth:8090/auth/oauth/user