server:
  port: 8004
spring:
  application:
    name: content-service
#security:
 # oauth2:
  #  resource:
   #   userInfoUri: http://oauth:8090/auth/oauth/user
eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka:8761/eureka/
  instance:
    preferIpAddress: true
    leaseRenewalIntervalInSeconds: 5
    metadataMap:
      instanceId: "${spring.application.name}:${random.value}"
management:
  endpoints:
    web:
      exposure:
        include: hystrix.stream
      base-path: /
auth:
  server:
    url: http://oauth:8090/auth/oauth/check_token
    clientId: messaging-client
    clientsecret: secret