server:
  port: 8090
  servlet:
    context-path: /auth
spring:
  application:
    name: oauth
#  jpa:
#    hibernate:
#      ddl-auto: update
#  datasource:
#    url: jdbc:postgresql://database:5432/db
#    username: admin
#    password: password1234

eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka:8761/eureka/
  instance:
    preferIpAddress: true
    leaseRenewalIntervalInSeconds: 5
    metadataMap:
      instanceId: "${spring.application.name}:${random.value}"